### ISSUE TITLE
Elapsed seems not to increment

### ISSUE THREAD

**Issue by MichaelXavier** [yamadapc/haskell-ascii-progress#20] opened 2016-08-19 21:33 UTC
I took the example code on the site:

```haskell
import           Control.Concurrent           (threadDelay)
import           Control.Monad                (unless)
import           System.Console.AsciiProgress

main :: IO ()
main = displayConsoleRegions $ do
   pg <- newProgressBar def { pgWidth = 100
                            , pgOnCompletion = Just "Done :percent after :elapsed seconds"
                            }
   loop pg
 where
   loop pg = do
       b <- isComplete pg
       unless b $ do
           threadDelay $ 200 * 1000
           tick pg
           loop pg
```

And ran it using the latest version 0.3.3.0 and noticed that the elapsed time never seems to stay up. The final completion output is: `Done 100% after   0.0 seconds` even though it took several seconds to complete.

**Comment by yamadapc** [comment] 2016-08-21 21:02
Could you post the dependencies you built it with, compiler version and platform? If you're using stack you should have the same dependencies as me, if you're using Cabal the `cabal freeze` output would be nice.

Works fine for me on OSX with 7.10, 8. Also tested Ubuntu and Fedora with GHC 7.10.3, 8.

If you don't mind, could you try these binaries?

Attached are 64-bit binaries of the examples for linux and osx that just require libgmp to be installed.

[ascii-progress-0.3.3.0.tar.gz](https://github.com/yamadapc/haskell-ascii-progress/files/429097/ascii-progress-0.3.3.0.tar.gz)

**Comment by yamadapc** [comment] 2016-09-06 14:57
Hey @MichaelXavier, closing because I can't reproduce. Please re-open if you can't use these packages.

**Closed by yamadapc** 2016-09-06 14:57 UTC
Labels: minor, waiting
